### ISSUE TITLE
How i can improve this app? (TODO LIST)

### ISSUE THREAD

**Issue by beastovsk** [beastovsk/yoldi-app#4]
**General**: 
- [ ] Show custom notifications after requests to API
- [ ] Fill the main page or remove it

**Profile**:
- [ ] After updating slug at edit form - slug at url won't update
- [ ] Validation of edit profile form
- [ ] Add submit modal window on sign out button
